version: '3.8'

services:
  # Frontend Web Server
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://localhost:3000"
    container_name: freelancer-frontend-standalone
    ports:
      - "80:80"
    networks:
      - freelancer-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  freelancer-network:
    driver: bridge